name: deb packaging

on:
  push:
    tags:
      - 'debian/*.*.*'
      - 'test/*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-native:
    uses: dionysius/gbp-gha/.github/workflows/gbp-native.yml@devel
    with:
      # https://github.com/orgs/community/discussions/26671
      DEBFULLNAME: dionysius (github-actions)
      DEBEMAIL: dragon.dionysius+gha@gmail.com
      before_build_deps_install: ""
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  release:
    if: startsWith(github.event.ref, 'refs/tags/debian')
    needs: [build-native]
    uses: dionysius/gbp-gha/.github/workflows/release.yml@devel
  upload:
    if: startsWith(github.event.ref, 'refs/tags/debian')
    needs: [build-native]
    uses: dionysius/gbp-gha/.github/workflows/upload-packagecloud.yml@devel
    with:
      USERREPO: dionysius/test
    secrets:
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
